name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove preview directory
        run: |
          if [ -d "pr-${{ github.event.pull_request.number }}" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git rm -rf pr-${{ github.event.pull_request.number }}
            git commit -m "Clean up preview for PR #${{ github.event.pull_request.number }}"
            git push
            echo "Preview cleaned up successfully"
          else
            echo "No preview directory found for PR #${{ github.event.pull_request.number }}"
          fi

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const body = `🧹 Preview deployment has been cleaned up.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body
            });
